### ISSUE TITLE
FR (?): connect to reverse-proxied hosts

### ISSUE THREAD

**Issue by sixtyfive** [thingalon/pony-ssh#14]
I have a lot of things like this in my `~/.ssh/config`, as I'm sure others do:

```
Host blah
  Hostname blah # only reachable from within blah's network
  ProxyCommand ssh blah-proxy -W %h:%p
```

None of the options from the README seem to support such a setup, I think Pony doesn't even read `~/.ssh/config`. Is there any, perhaps undocumented, way of connecting to a host such as "blah"?

**Comment by thingalon** [comment]
Pony-SSH doesn't have in-built proxy connection support at this time, though I would be completely open to receiving a PR to add the feature. :)

In the meantime, I think you can set this up by manually opening a forwarding connection to your proxy.

Try this: In a terminal (or WSL session if you're on Windows), open a connection to your proxy host forwarding a local port of your choice to port 22 on your destination machine: 
```
ssh -L 2222:your.target.server.com:22 your.proxy.server.com
```

Once you've done that, any connections to port 2222 on your local machine should get forwarded to port 22 on your.target.server.com

From there, you should be able to connect using a Pony-SSH config like this: 
```
"proxied-host": {
    "host": "localhost",
    "port": 2222,
    "username": "username-from-the-target-server",
    "agent": true,
}
```

I know it's not as convenient as having in-built proxy support in Pony-SSH, but hopefully this can get you up and running for now. Let me know how you get on.

**Comment by sixtyfive** [comment]
Oh dang, of course, why didn't I think of that–thank you very much, @thingalon! Unfortunately with the current situation & "home"-"office" there's no way I can get into a new language/environment atm. Hopefully someone who already has some experience with writing VSCode plugins will come along and treat us to that PR at some point :)
