### ISSUE TITLE
.git folder ignored?

### ISSUE THREAD

**Issue by toastbrotch** [thingalon/pony-ssh#19]
as far as i tried vsc does not discover my .git folder on the target server, and therefore the remote-folder is not a git-repo... fixable or do i miss some configuration? would be nice to get this working (my ssh-user has the rights and that .git folder is visible if i remove the exclude in the vsc config)

**Comment by thingalon** [comment]
There are a few things going on here.

The first problem is that VSCode's git plugins don't talk to Pony SSH (or any other filesystem plugin) about what paths are available. They assume they can read the local filesystem, and bypass any filesystem plugins to do so. So, the git plugins simply won't see remote repositories supplied by any filesystem plugin.

The reason `.git` folders don't appear in your file explorer at all is that they are excluded by default in VSCode's settings. Check out the "Files: Exclude" setting in VSCode. If you would like to see your `.git` folders, you can remove them from the exclusion list - but this will not cause them to integrate nicely with VSCode's git support.

I'm sorry to say that Pony SSH can't offer nice git integration; it's simply a limitation of filesystem plugins in VSCode.

However, [Microsoft's Remote SSH plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) works differently - and can integrate with git. Remote SSH doesn't register a new filesystem with the editor - instead it opens an SSH connection to your remote host and runs another (headless) copy of VSCode on your remote system. It runs your plugins there, where they _can_ see all the files on your remote filesystem - and just runs its User Interface locally on your machine.

As a result, Pony SSH is a bit faster and more light-weight, but Remote SSH offers full remote integration at a level that filesystem plugins simply can't.

Sorry to disappoint. :)

**Comment by toastbrotch** [comment]
thanx for clarification
remote-ssh plugin is not working on my server...
