### ISSUE TITLE
failed to purge cache folders from deleted hosts: ENOENT: no such file or directory, scandir 

### ISSUE THREAD

**Issue by mike-pt** [thingalon/pony-ssh#3]
First of, thanks for this, works perfect in OSX with "agent" :)

However I do see an error, that seem to be about just failing to create cache dirs:

`[2019-04-21 19:06:28] [warn] Error while cleaning up cache directory: ENOENT: no such file or directory, scandir '/Users/userA/Library/Application Support/Code/User/globalStorage/thingalon.pony-ssh/cache/testSSH/files'

**Comment by thingalon** [comment]
Thanks for the report @mike-pt. I've pushed a patch, and will release it in a new version soon. :)
