### ISSUE TITLE
Could not resolve workspace folder

### ISSUE THREAD

**Issue by shisif** [thingalon/pony-ssh#4]
setting:
{
    "ponyssh.hosts": { 
        "my-host": {
           "host": <>,
           "username": <>,
           "agent": true
        }
      },

connection is set and initialized.
but when I try to open remote folder it is unable to resolve folder

![image](https://user-images.githubusercontent.com/52562042/60705810-b6251280-9f25-11e9-8506-8947fa579515.png)

**Comment by thingalon** [comment]
If you're having connection issues, I recommend that you check out the Pony SSH Logs for more information, for clues as to what may have gone wrong.

1. Open the Output panel (ctrl-shift-u on Windows, or cmd-shift-u on Mac)
2. From the drop-down list in the top-right of the Output panel, select "Pony SSH Logs".

The log should show details of any errors that occured while Pony SSH tried to connect to your server, and will hopefully shed some light on what's gone wrong.

**Comment by thingalon** [comment]
Closing: inactive.
