### ISSUE TITLE
Feature request: new option "executeCommand"

### ISSUE THREAD

**Issue by Eichhorst** [thingalon/pony-ssh#5]
If _executeCommand_ is specified, it is executed on the remote host on login.

**Comment by thingalon** [comment]
Hi @Eichhorst.

What kind of commands are you thinking of executing? Something that sets up stuff and exits quickly (eg: a `.profile`-like command), or something that runs continuously while Pony SSH is connected to the host?

I want to understand the use-case before designing new features.

**Comment by Eichhorst** [comment]
Hi,
first of all: thanks for your work and your reply!

my use-case would be to execute sudo -i automatically.
I would like to use workspace environments, which files require root permission.

best,
Tom

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thingalon** [comment]
Hi Tom. Apologies for the slow response.

I've been thinking about how best to implement this. Pony-ssh uses ssh exec multiple times when setting up a session, so calling `sudo -i` once on connection won't do the trick.

I've prepared a new update which allows you to specify a custom shell command; which will allow you to call `sudo` automatically with a config like this: 

```
 "ponyssh.hosts": {
    "example-sudo": {
       "host": "example.com",
       "username": "my-login",
       "agent": true,
       "shell": "sudo sh -c"
    }
  }
```

With the above setup, pony-ssh would allow you to edit any files that you can via `sudo` - though it does require that your user can sudo without using a password on the remote host.

Before I roll this out and turn it into a new version, I wanted to check in with you if this sounds like it could solve your problem.

https://github.com/thingalon/pony-ssh/pull/6

**Comment by Eichhorst** [comment]
Hi,

nothing to apologize for!
sudo-ing without pw is no problem.
will it be possible to edit any root-files by defining "shell": "sudo bash -i" then?

Thanks again for your work!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thingalon** [comment]
I've just released an update to Pony-SSH which will hopefully meet your needs. try adding the following to your configuration: 
`"shell": "sudo bash -c"`

Don't use the `-i` parameter; it will kick off an interactive shell, which won't work with pony-ssh. :)

Hope this helps you out. Let me know if you run into trouble.

**Comment by Eichhorst** [comment]
works perfectly, thx!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thingalon** [comment]
👍 Glad I could help.
